### PR TITLE
added a wide string version of the entry set message function using a single string

### PR DESCRIPTION
**Pull request by abhakta-47**
added a wide string version of the entry set message function using a single string as described in #272

### CODE REVIEW

**Comment by abhakta-47** [comment]
`SetMessageWideStrTest.MallocFailureOnMessage` is failing.
I used existing `SetMessageStrTest.MallocFailureOnMessage` as template. Some tests are giving error code 24 (invalid encoding).
I am not sure what it is the issue maybe `set_malloc_result = stumpless_set_malloc( MALLOC_FAIL_ON_SIZE( 46 ) );` malloc size wouldn't be 46 ?

**Comment by abhakta-47** [comment]
Also, how to create an invalid wide string to test for invalid wide string ?

**Comment by goatshriek** [comment]
You may be seeing failures in the malloc test that you mentioned because of an issue with the function as a whole, not just the malloc failure portion. Be sure that you add a test that validates normal functionality, since right now all of your tests only cover error scenarios, and see if this fails as well. You may need to investigate the implementation of `config_copy_wstring_to_cstring` while troubleshooting, since this is the first significant usage of this function. There may be an error in that function's implementation.

For an invalid wide string, try constructing a string with invalid surrogates. You should be able to find examples of this in UTF-16 descriptions, including the [Wikipedia page](https://en.wikipedia.org/wiki/UTF-16).

**Comment by abhakta-47** [comment]
```
#  ifdef HAVE_WINDOWS_H
#    include "private/config/have_windows.h"
#    define config_copy_wstring_to_cstring  windows_copy_wstring_to_cstring
#  elif HAVE_WCHAR_H
#    include "private/config/have_wchar.h"
#    define config_copy_wstring_to_cstring wchar_copy_wstring_to_cstring
#  else
#    include "private/config/fallback.h"
#    define config_copy_wstring_to_cstring  fallback_copy_wstring_to_cstring
#  endif
```

In `HAVE_WCHAR_H` case `wchar_copy_wstring_to_cstring` is working well.
So, I commented out that case to force use fallback funtions.
In fallback case there are linking errors during build.
`[build] /usr/bin/ld: libstumpless.so.2.1.0: undefined reference to 'fallback_copy_wstring_to_cstring'`

**Comment by goatshriek** [comment]
That is due to the `src/config/fallback.c` module not being included during compilation as it is not needed by your system configuration. Since this wasn't used in your tests, it's unlikely to be the source of the problems you're seeing. Instead, try adding some print statements or debugging `wchar_copy_wstring_to_cstring` to see if it is behaving as you expect.

**Comment by goatshriek** [comment]
Just checking in to see if this is still underway.

**Comment by goatshriek** [comment]
Closing as stale.

**Pull request closed without merging**
