### PR TITLE
Adding Hindi for localisation

### PR DESCRIPTION
**Pull request by viveknshah**
Describe the overall purpose of your pull request in a few sentences, keeping
things at a high level. If this request is in response to a particular issue,
include a reference to it here.

Make sure that your pull request follows the guidelines specified in the
[Guidelines for Contributing](../docs/CONTRIBUTING.md).

### CODE REVIEW

**Review by goatshriek — CHANGES_REQUESTED** [review]
This looks good! Only two things to fix: break up the lines longer than 80 characters flagged by the CI check, and add a flag to the README list of localizations to reflect your hard work!

**Comment by viveknshah** [comment]
> This looks good! Only two things to fix: break up the lines longer than 80 characters flagged by the CI check, and add a flag to the README list of localizations to reflect your hard work!

Made the requested changes.

**Comment by goatshriek** [comment]
Almost there! Just one more line to correct.

**Comment by viveknshah** [comment]
> Almost there! Just one more line to correct.

that was too close for comfort. Wrapped it now

**Review by goatshriek — APPROVED** [review]

**Comment by viveknshah** [comment]
Out of curiosity, do I need to do anything additional for the merge or that's more on the maintainer's court now?

**Comment by goatshriek** [comment]
I will finish the merge and tag it within the next 8 hours or so, no further action for you.

**Pull request merged**
