### PR TITLE
Fixes #295: factor config_get_now out of wrapper.h

### LINKED ISSUE #295: factor config_get_now out of wrapper.h
Stumpless uses a scheme involving `#define`names and macro functions to separate its portability measures from the application logic itself. This was originally done via a single header, `include/private/config/wrapper.h`, but as the library grew this single header became bloated. Now features are instead contained in their own dedicated wrapper headers. Older features and functions need to be moved to their own as well to address the original problem.

Your task here is to factor the function used to retrieve the current time into it's own header. This is a good task for those with some C knowledge looking to learn about how to implement portability in a C application. As this is a refactoring task you can rely on the existing unit and integration tests as a safety net as you make changes and explore.

Check out the [Contributing Guidelines](https://github.com/goatshriek/stumpless/blob/latest/docs/CONTRIBUTING.md) and the [development guide](https://github.com/goatshriek/stumpless/blob/latest/docs/development.md) for the basics on working with stumpless and submitting changes.

## General Approach
There are a few details left out of the following approach, for you to fill in as you encounter them. If you find you need help, please ask here or on the [project gitter](https://gitter.im/stumpless/community) and someone can help you get past the stumbling block.

97698be5b62c3fd1dddfd953db15a5c7265b896c is an implementation of a very similar task: you can use this commit as a template for this task.

First, read through the [portability documentation](https://github.com/goatshriek/stumpless/blob/latest/docs/portability.md) to understand how portability is approached in the library.

Next, have a look at `include/private/config/wrapper/wstring.h`. This header does the same wrapping for wide string support functions in the library. This is a great file to copy as a starting point and modify to suit your needs. The new header should be `include/private/config/wrapper/get_now.h`.

Finally, have a look at `tools/check_headers/stumpless_private.yml`. This file is used by a custom tool for header inclusion checks across the library's source code. You'll need to add an entry for `config_get_now` to this file, pointing to your newly created header.

Once you have moved things to your new header and updated the header checking tool manifests, you can use the header check tool to tell you what files need to have their `#include` statements updated. You can find examples of how to run the tool in the testing workflow that does it, `.github/workflows/analysis.yml`, or you can use the one-liner included below. You will need Ruby to run the tool.

```sh
tools/check_headers/check_headers.rb "include/**/*.h*" "include/**/**.h*" "src/**/*.c" "test/**/*.cpp" "docs/examples/**/*.c"
```

Good luck!

### PR DESCRIPTION
**Pull request by Sakshi-75**
Describe the overall purpose of your pull request in a few sentences, keeping
things at a high level. If this request is in response to a particular issue,
include a reference to it here.

Make sure that your pull request follows the guidelines specified in the
[Guidelines for Contributing](../docs/CONTRIBUTING.md). 
Fixes #295 
Factor config_get_now out of wrapper.h

### CODE REVIEW

**Review by goatshriek — CHANGES_REQUESTED** [review]
This all looks fine! The static analysis is failing because some older symbols don't have entries in the header manifest. Please add `HAVE_VSNPRINTF_S` and `HAVE_FOPEN_S` to the `tools/check_headers/stumpless_private.yml` pointing to `private/config.h`, which should resolve this.

**Review by goatshriek — APPROVED** [review]

**Comment by goatshriek** [comment]
Almost there @Sakshi-75! There are two files in `src/` that can have the `#include` statement for the wrapper header removed from them. Once you remove those statements the header check should pass. See the `Static Analysis / custom analysis` action results for the details.

**Comment by Sakshi-75** [comment]
Hi @goatshriek ,
I removed those unused include statements. Can you check once more?

**Comment by goatshriek** [comment]
Looks like that did it! Thanks very much for putting this together!

**Pull request merged**
