### PR TITLE
Add localization for Albanian (sq-AL)

### PR DESCRIPTION
**Pull request by heavylemon1**
This pull request solves #324 by adding localization support for the :albania: Albanian language (sq-AL).
There are some terms which don't have a very descriptive translation in Albanian, for which I also included the English term for better readability.
Let me know if you have any further questions or if something doesn't check out.
Thanks!

### CODE REVIEW

**Comment by goatshriek** [comment]
Thanks very much for putting this together, it looks great! You just need to break up the lines that are longer than 80 characters, and this should be good to accept.

**Review by goatshriek — CHANGES_REQUESTED** [review]
Break up lines longer than 80 characters so that static analysis passes.

**Comment by heavylemon1** [comment]
Hello @goatshriek ,
Just divided the strings that failed the checks to several lines
Let me know if there are more improvements to be made!

**Review by goatshriek — APPROVED** [review]

**Comment by goatshriek** [comment]
Thank you once again for putting this localization together! It is greatly appreciated.

**Comment by heavylemon1** [comment]
You're welcome @goatshriek !
Appreciate the opportunity as well.

**Pull request merged**
