### PR TITLE
Made Changes as per Issue #162

### PR DESCRIPTION
**Pull request by ShobhitSamuelSingh**
Please check if the changes made are correct, and please guide me about how to add test cases.

### CODE REVIEW

**Comment by goatshriek** [comment]
It looks like there are some issues with compilation - take a look at your updates to `src/target/stream.c`, which has code outside of a function (starting on line 49) and references a string literal macro as a function (on line 40). Running the `check` target (for example `make check` in a Makefile-based build) on your code will let you verify that everything builds and no existing tests are breaking.

It also appears that you have checked for a buffer target type in every function, instead of the respective type. For example, the check in `src/target/file.c` should make sure that the target type is `STUMPLESS_FILE_TARGET`. You could leave it this way to validate that your tests fail, but just be sure you do fix it afterwards to get the tests passing.

Regarding testing - I'll walk you through the buffer target test first. Once you get this working, you would do essentially the same thing for the other target types.

First, look for the test of the `stumpless_close_buffer_target` function that passes in a NULL target. For the buffer targets, this is at line 271 of `test/function/target/buffer.cpp`. Make a copy this test directly below the existing one, and name the new one something fitting, perhaps `TEST(BufferTargetCloseTest, WrongTargetType )`. Next, create a new target that is _not_ a buffer target; I recommend using `stumpless_open_stdout_target` for this. Pass this as the argument to the close function (instead of NULL). Change the expected error id to be `STUMPLESS_TARGET_INCOMPATIBLE`. Finally, be sure you close the target you created (you can just use `stumpless_close_target` for this). You can then run the `check` target to make sure that all of the tests pass, including your new one.

**Comment by goatshriek** [comment]
This pull has been marked as stale since there have been no updates in the last two months. It will be closed after another month of inactivity.

**Comment by ShobhitSamuelSingh** [comment]
I am so sorry for the late reply, but this is just because my exams were going on and they have finally ended now.
I would like to request you to please close this pull request as I am still a beginner and it's getting slightly difficult for me to understand. Thank you so much for all your guidance. I hope I can contribute to this project in some other way afterward.

**Comment by goatshriek** [comment]
No problem at all! I hope that you picked up some useful tidbits while working on this, and that you come back once you've got a better handle on things!

**Pull request closed without merging**
