### PR TITLE
Update CMakeLists.txt

### PR DESCRIPTION
**Pull request by Sanidhyafeaturist**
So according to issue #449 I have added a custom function in CmakeLists.txt

### CODE REVIEW

**Comment by goatshriek** [comment]
You'll need to implement the new benchmark tests as well, as described in the issue. Once you're finished, mark this PR as ready for review and I'll take a look at it.

**Comment by Sanidhyafeaturist** [comment]
ok

**Comment by Sanidhyafeaturist** [comment]
check my pull request at #460

**Comment by Sanidhyafeaturist** [comment]
check my pull request #460

**Pull request closed without merging**
